export const wordList  = [
    // Nepali Foods
    "Momo",
    "Selroti",
    "Dhido",
    "Gundruk",
    "Thukpa",
    "Yomari",
    "Choila",
    "Bara",
    "Laphing",
    "Kwati",
    "Chatamari",
    "Juju Dhau",
    "Aloo Tama",
    "Samay Baji",
  
    // Western Foods
    "Pizza",
    "Burger",
    "Pasta",
    "Hotdog",
    "Fries",
    "Salad",
    "Steak",
    "Sushi",
    "Tacos",
    "Donut",
    "Sandwich",
    "Spaghetti",
    "Nuggets",
    "Cheesecake",
    "Icecream",
  ];
  